export const studio = [
  {
    id: "englivo",
    name: "Englivo",
    status: "Production",
    description: "AI-powered fluency engine for natural English speaking.",
    ownership: "Product Engineer • Vaidik Eduservices",
    type: "professional",
    link: "https://naturalfluency.vercel.app",
  },
  {
    id: "vaidik",
    name: "Vaidik Tutoring",
    status: "Production",
    description: "K12 and test-prep tutoring marketplace and student OS.",
    ownership: "Product Engineer • Vaidik Eduservices",
    type: "professional",
    link: "https://vaidiktutorin.vercel.app",
  },
  {
    id: "wehostt",
    name: "WeHostt",
    status: "Live",
    description: "Revenue SaaS for hospitality lead capture and client routing.",
    ownership: "Product Engineer • Vaidik Eduservices",
    type: "professional",
    link: "https://www.wehostt.com",
  },
  {
    id: "tutoring-engine",
    name: "Tutoring Engine",
    status: "Production",
    description: "Multi-role booking, messaging, and payments infrastructure.",
    ownership: "Product Engineer • Vaidik Eduservices",
    type: "professional",
    link: null,
  },
  {
    id: "vibespark",
    name: "Vibespark",
    status: "In Development",
    description: "Real-time voice and video platform using WebRTC and sockets.",
    ownership: "Independent R&D Lab",
    type: "independent",
    link: null,
  },
];
